PREFIX foaf: <http://xmlns.com/foaf/0.1/>

PREFIX iuf: <http://ex.org/iuf/>

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX geo: <https://www.w3.org/2003/01/geo/>



CONSTRUCT {
  
?URI a foaf:Person;
  	
	dbo:year ?annee;
    
	foaf:lastName ?nom;
    
	foaf:givenName ?prenom;
     
	iuf:categorie_iuf ?categorie_iuf;
       
	iuf:reconduction_iuf ?reconduction_iuf;
    
	foaf:gender ?sexe;
       
	iuf:section_cnu ?section_cnu;
      
	iuf:groupe_cnu ?groupe_cnu;
       
	iuf:secteur_disciplinaire ?secteur_disciplinaire;

	iuf:groupe_de_corps ?groupe_de_corps;
 
	iuf:numero_national_de_structure_de_recherche ?numero_national_de_structure_de_recherche;
    
	iuf:unite_de_recherche ?unite_de_recherche;
 
	iuf:academie ?academie;
       
	dbo:region ?region;
      
	iuf:pres ?pres;
        
	iuf:idex ?idex;
    
	geo:lat ?latitude;
	geo:long ?longitude;
	iuf:discipline_nomenclature ?discipline_nomenclature;
    
	dbo:EducationalInstitution ?etablissement. 
} 

FROM <file:fr-esr-iuf-les-membres.csv> 

WHERE {

	BIND (URI(CONCAT('http://iuf.org/Member/', ?nom, '_', ?prenom)) AS ?URI)

}


-